name: relinc-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: install-go

    # - name: Get all dependencies
    #   run: go build -v ./...

    # - name: Build
    #   run: go build -v ./...

    - name: Test
      run: make test
