// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package db

import (
	"time"
)

type Account struct {
	ID          int64     `json:"id"`
	Owner       int64     `json:"owner"`
	Balance     int64     `json:"balance"`
	Currency    string    `json:"currency"`
	AccountType string    `json:"account_type"`
	CreatedAt   time.Time `json:"created_at"`
}

type Entry struct {
	ID        int64 `json:"id"`
	AccountID int64 `json:"account_id"`
	// Can be negative or positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type Transfer struct {
	ID            int64 `json:"id"`
	FromAccountID int64 `json:"from_account_id"`
	ToAccountID   int64 `json:"to_account_id"`
	// It must be positive
	Amount    int64     `json:"amount"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	FirstName      string    `json:"first_name"`
	LastName       string    `json:"last_name"`
	EmailAddress   string    `json:"email_address"`
	PhoneNumber    string    `json:"phone_number"`
	Username       string    `json:"username"`
	Dob            time.Time `json:"dob"`
	Address        string    `json:"address"`
	ProfilePicture string    `json:"profile_picture"`
	Gender         string    `json:"gender"`
	CreatedAt      time.Time `json:"created_at"`
}
