name: relinc-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      # postgres:
      #   # Docker Hub image
      #   image: postgres:13
      #   env:
      #     POSTGRES_USER: root
      #     POSTGRES_DB: relinc_db
      #     POSTGRES_PASSWORD: root
      #   # Set health checks to wait until postgres has started
      #   options: >-
      #     --health-cmd pg_isready
      #     --health-interval 10s
      #     --health-timeout 5s
      #     --health-retries 5
      #   ports:
      #     - 5432:5432

      # services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: root
          POSTGRES_DB: relinc_db
          POSTGRES_PASSWORD: root
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: install-go


    - name: Checkout code into the go module directory
      uses: actions/checkout@v3

    - name: install go migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.12.2/migrate.linux-amd64.tar.gz | tar xvz
        echo "------------------"
        ls
        sudo mv migrate.linux-amd64 /usr/bin/
        echo "++++++++++++"
        which migrate

    - name: Run Migrations
      run: make migrateupcicd

    - name: Test
      run: make test
