name: relinc-ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:13
        
        env:
          POSTGRES_USER: root
          POSTGRES_DB: relinc_db
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
      id: install-go


    - name: Checkout code into the go module directory
      uses: actions/checkout@v3

    - name: Run Migrations
      run: make migrateup

    - name: Test
      run: make test
